[package]
name = "rs-reference"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
nimiq-account = { git = "https://github.com/nimiq/core-rs-albatross" }
nimiq-database = { git = "https://github.com/nimiq/core-rs-albatross" }
nimiq-hash = { git = "https://github.com/nimiq/core-rs-albatross" }
nimiq-keys = { git = "https://github.com/nimiq/core-rs-albatross" }
nimiq-primitives = { git = "https://github.com/nimiq/core-rs-albatross" }
nimiq-serde = { git = "https://github.com/nimiq/core-rs-albatross" }
nimiq-trie = { git = "https://github.com/nimiq/core-rs-albatross" }
