# Do not manually edit this file, it is managed by Gleam.
#
# This file locks the dependency versions used, to make your build
# deterministic and to prevent unexpected versions from being included
# in your application.
#
# You should check this file into your source control repository.

packages = [
  { name = "blake2", version = "1.0.4", build_tools = ["mix"], requirements = [], otp_app = "blake2", source = "hex", outer_checksum = "E9F4120D163BA14D86304195E50745FA18483E6AD2BE94C864AE449BBDD6A189" },
  { name = "ed25519", version = "1.5.1", build_tools = ["mix"], requirements = [], otp_app = "ed25519", source = "hex", outer_checksum = "F83F7B346EDFB91F0672682DEE8672D16A26BFA8A7B85EE9795CB7FB2825B8BB" },
  { name = "gblake2", version = "1.0.1", build_tools = ["gleam"], requirements = ["blake2", "gleam_stdlib"], otp_app = "gblake2", source = "hex", outer_checksum = "95862F2B64587519593F4D4E42BCF39179ED2D0AC93538B1F4611D15538D9571" },
  { name = "ged25519", version = "1.0.2", build_tools = ["gleam"], requirements = ["ed25519", "gleam_stdlib"], otp_app = "ged25519", source = "hex", outer_checksum = "94F5919CC9FBB9B9EFECD8E073995EEA116ACB3C499F8854B648BC22A703942D" },
  { name = "gleam_stdlib", version = "1.0.3", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "1F543AFBA5D33DA493E6087F4E4C4F20D899411343512686C98A8ABB2963CF22" },
  { name = "gleeunit", version = "1.11.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleeunit", source = "hex", outer_checksum = "EC31ABA74256AEA531EDF8169931D775BBB384FED0A8A1BDC4DD9354E3E21826" },
  { name = "gvarint", version = "1.0.2", build_tools = ["gleam"], requirements = ["gleam_stdlib", "varint"], otp_app = "gvarint", source = "hex", outer_checksum = "D8761B7FB70BE719D92F123E4AF7817F02F4CCCB692A715A05B6DE826717257D" },
  { name = "nimiq_address", version = "1.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "nimiq_address", source = "hex", outer_checksum = "8C6D8B7830F5D6547715C143D33E8FE90B1EC759A5C4D90133E471B76BCD6C0D" },
  { name = "nimiq_blake2b", version = "1.0.0", build_tools = ["gleam"], requirements = ["gblake2", "gleam_stdlib"], otp_app = "nimiq_blake2b", source = "hex", outer_checksum = "3C650D957243A9D6412A40C1A20108C06B3422DB487C4127751DCF059CAD4854" },
  { name = "nimiq_bls", version = "1.0.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "nimiq_bls", source = "hex", outer_checksum = "573EE2F9B844DFF15310750DD3A29B8819DEF05233D9E16B024E1BDFCF93DCBD" },
  { name = "nimiq_serde", version = "1.0.1", build_tools = ["gleam"], requirements = ["gleam_stdlib", "gvarint"], otp_app = "nimiq_serde", source = "hex", outer_checksum = "CC4B4928D833E71AF7ABDF98800A7B164CD77DB27196354EDC587ED275818904" },
  { name = "varint", version = "1.6.0", build_tools = ["mix"], requirements = [], otp_app = "varint", source = "hex", outer_checksum = "2B4F4A20650AEEBE993A70B03BB99571BCBDDC27C361322C28B586D8A772CE4E" },
]

[requirements]
ged25519 = { version = ">= 1.0.0 and < 2.0.0" }
gleam_stdlib = { version = ">= 0.34.0 and < 2.0.0" }
gleeunit = { version = ">= 1.0.0 and < 2.0.0" }
nimiq_address = { version = ">= 1.0.0 and < 2.0.0" }
nimiq_blake2b = { version = ">= 1.0.0 and < 2.0.0" }
nimiq_bls = { version = ">= 1.0.0 and < 2.0.0" }
nimiq_serde = { version = ">= 1.0.0 and < 2.0.0" }
