name = "nimiq_bls"
version = "1.0.0"

description = "Nimiq-style BLS keys and signatures for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sisou", repo = "nimiq_gleam" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
