# Do not manually edit this file, it is managed by Gleam.
#
# This file locks the dependency versions used, to make your build
# deterministic and to prevent unexpected versions from being included
# in your application.
#
# You should check this file into your source control repository.

packages = [
  { name = "gleam_stdlib", version = "1.0.3", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "1F543AFBA5D33DA493E6087F4E4C4F20D899411343512686C98A8ABB2963CF22" },
  { name = "gleeunit", version = "1.11.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleeunit", source = "hex", outer_checksum = "EC31ABA74256AEA531EDF8169931D775BBB384FED0A8A1BDC4DD9354E3E21826" },
  { name = "gvarint", version = "1.0.2", build_tools = ["gleam"], requirements = ["gleam_stdlib", "varint"], otp_app = "gvarint", source = "hex", outer_checksum = "D8761B7FB70BE719D92F123E4AF7817F02F4CCCB692A715A05B6DE826717257D" },
  { name = "varint", version = "1.6.0", build_tools = ["mix"], requirements = [], otp_app = "varint", source = "hex", outer_checksum = "2B4F4A20650AEEBE993A70B03BB99571BCBDDC27C361322C28B586D8A772CE4E" },
]

[requirements]
gleam_stdlib = { version = ">= 0.44.0 and < 2.0.0" }
gleeunit = { version = ">= 1.0.0 and < 2.0.0" }
gvarint = { version = ">= 1.0.0 and < 2.0.0" }
