name = "gblake2"
version = "1.0.1"

description = "BLAKE2 hash functions - Gleam bindings for the Elixir `blake2` package."
licences = ["Apache-2.0"]
repository = { type = "github", user = "sisou", repo = "nimiq_gleam" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
blake2 = ">= 1.0.4 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
