name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      valkey:
        image: valkey/valkey:alpine
        ports:
          - 6379:6379
    strategy:
      matrix:
        package: [
          gblake2,
          ged25519,
          gvarint,
          nimiq_address,
          nimiq_blake2b,
          nimiq_bls,
          nimiq_cli,
          nimiq_gleam,
          nimiq_serde,
          nimiq_trie,
        ]

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1"
          rebar3-version: "3"
          elixir-version: "1"
      - run: gleam deps download
        working-directory: ${{ matrix.package }}
      - run: gleam test
        working-directory: ${{ matrix.package }}
      - run: gleam format --check src test
        working-directory: ${{ matrix.package }}
